// PDF Generation for certificates

async function generatePDF() {
    const { jsPDF } = window.jspdf;
    const config = municipalities[currentMunicipality];
    
    // Create PDF document
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });
    
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;
    
    // Header
    doc.setFontSize(20);
    doc.text('AMPHR', 20, yPosition);
    yPosition += 10;
    
    doc.setFontSize(14);
    doc.text(currentMunicipality === 'dm' ? 
        'Dubai Municipality QS Certificate' : 
        'Abu Dhabi Municipality Occupancy Certificate', 20, yPosition);
    yPosition += 15;
    
    // Building Information
    doc.setFontSize(12);
    doc.text('Building Information', 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    const buildingName = document.getElementById('buildingName').value || 'N/A';
    const location = document.getElementById('buildingLocation').value || 'N/A';
    const yearBuilt = document.getElementById('buildingYear').value || 'N/A';
    
    doc.text(`Name: ${buildingName}`, 20, yPosition);
    yPosition += 7;
    doc.text(`Location: ${location}`, 20, yPosition);
    yPosition += 7;
    doc.text(`Year Built: ${yearBuilt}`, 20, yPosition);
    yPosition += 7;
    
    const timestamp = new Date().toLocaleDateString('en-AE');
    doc.text(`Certificate Date: ${timestamp}`, 20, yPosition);
    yPosition += 15;
    
    // Health Score
    doc.setFontSize(12);
    doc.text('Health Score Assessment', 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    const score = inspectionData.score || 0;
    doc.text(`Overall Health Score: ${score}/100`, 20, yPosition);
    yPosition += 7;
    
    // Score breakdown
    Object.entries(config.healthScoreWeights).forEach(([category, weight]) => {
        const inputElement = document.querySelector(`input[data-category="${category}"]`);
        const value = inputElement ? inputElement.value : '0';
        const label = category.replace(/_/g, ' ').toUpperCase();
        const percentage = (weight * 100).toFixed(0);
        doc.text(`${label} (${percentage}%): ${value}/100`, 25, yPosition);
        yPosition += 6;
    });
    
    yPosition += 5;
    
    // Certificate Status
    doc.setFontSize(12);
    doc.text('Certificate Status', 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    const status = inspectionData.status || 'No Data';
    const validity = inspectionData.validity || 'N/A';
    doc.text(`Status: ${status}`, 20, yPosition);
    yPosition += 7;
    doc.text(`Valid for: ${validity}`, 20, yPosition);
    yPosition += 15;
    
    // Inspection Summary
    doc.setFontSize(12);
    doc.text('Inspection Summary', 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    const completedItems = inspectionData.completedItems || 0;
    const totalItems = inspectionData.totalItems || 0;
    doc.text(`Items Completed: ${completedItems}/${totalItems}`, 20, yPosition);
    yPosition += 10;
    
    // Footer
    yPosition = pageHeight - 20;
    doc.setFontSize(8);
    doc.text('This certificate is generated by AMPHR', 20, yPosition);
    doc.text(`${currentMunicipality.toUpperCase()} | ${timestamp}`, 20, yPosition + 5);
    
    // Save PDF
    const fileName = `AMPHR_${currentMunicipality.toUpperCase()}_${buildingName.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
    doc.save(fileName);
}
